# Generated by Django 5.1.1 on 2025-11-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Pay at Counter'), ('online', 'Paid Online')], default='cod', max_length=10),
        ),
    ]
